// <auto-generated />
using LEMED.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LEMED.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720172653_AddProductsData")]
    partial class AddProductsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LEMED.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "/images/hobobag.jpg",
                            Name = "Hobo Bag",
                            NameFA = "کیف هوبو",
                            Price = 189,
                            Tag = "New"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&q=80",
                            Name = "Tote Bag",
                            NameFA = "کیف توت",
                            Price = 145,
                            Tag = ""
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://localhost:7088/images/dufflebag.jpg",
                            Name = "Duffle Bag",
                            NameFA = "کیف دافل",
                            Price = 220,
                            Tag = "Sale"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://localhost:7088/images/clutchbag.jpg",
                            Name = "Clutch ",
                            NameFA = "کیف کلاچ",
                            Price = 96,
                            Tag = "Sale"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
